name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build / Start Services
        run: docker compose up -d --build

      - name: Check Container Status
        run: docker ps

      - name: Wait for Database
        run: sleep 15

      - name: Verify
        run: |
          curl http://localhost:3000

      - name: Stop Services
        if: always()
        run: docker compose down